double u0[] = {0.40427292089515005, -0.6348080638911874, -0.5826808357272043};
double u1[] = {-0.48512750507418756, 0.761769676669425, 0.6992170028726451};

double p0[] = {3.5232428618986744, 1.8252391089351945, 60.277945706722875};
double p1[] = {0.7003134205554864, 2.0890725392537743, 0.7789572738382433};

double c = 6.194008413911195;

void setup() {
    Serial.begin(9600);
}

void loop() {
    //Data Section: To Be Coded Manually

    float data[3]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double term1 = 0.0;
    double term2 = 0.0;

    for(int i=0; i<3; i++)
    {
        term1 += p0[i] * (data[i] - u0[i]) * (data[i] - u0[i]);
        term2 += p1[i] * (data[i] - u1[i]) * (data[i] - u1[i]);
    }

    double temp = term1 - term2;

    if(temp >= c)
    {
        //Do something for class label ulat_daun=tinggi,ulat_krop=tinggi,busuk_hitam=tinggi.
        Serial.println("ulat_daun=tinggi,ulat_krop=tinggi,busuk_hitam=tinggi");
    }
    else
    {
        //Do something for class label ulat_daun=rendah,ulat_krop=rendah,busuk_hitam=rendah.
        Serial.println("ulat_daun=rendah,ulat_krop=rendah,busuk_hitam=rendah"); 
    }

    delay(1000);
}//This code was autogenerated using micro-learn.
//Use the dummy variable array 'data' to interact with the ML inference.

double u0[] = {0.40427292089515005, -0.6348080638911874, -0.5826808357272043};
double u1[] = {-0.48512750507418756, 0.761769676669425, 0.6992170028726451};

double p0[] = {3.5232428618986744, 1.8252391089351945, 60.277945706722875};
double p1[] = {0.7003134205554864, 2.0890725392537743, 0.7789572738382433};

double c = 6.194008413911195;

void setup() {
    Serial.begin(9600);

}

void loop() {
    //Data Section: To Be Coded Manually

    float data[3]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double term1 = 0.0;
    double term2 = 0.0;

    for(int i=0; i<3; i++)
    {
        term1 += p0[i] * (data[i] - u0[i]) * (data[i] - u0[i]);
        term2 += p1[i] * (data[i] - u1[i]) * (data[i] - u1[i]);
    }

    double temp = term1 - term2;

    if(temp >= c)
    {
        //Do something for class label ulat_daun=tinggi,ulat_krop=tinggi,busuk_hitam=tinggi.
        Serial.println("ulat_daun=tinggi,ulat_krop=tinggi,busuk_hitam=tinggi");
    }
    else
    {
        //Do something for class label ulat_daun=rendah,ulat_krop=rendah,busuk_hitam=rendah.
        Serial.println("ulat_daun=rendah,ulat_krop=rendah,busuk_hitam=rendah"); 
    }

    delay(1000);
}
